#!/usr/bin/perl
# Copyright (C) 2017 Asher Blum

use strict;
use Data::Dumper;

# Generate all sounds specified in spec.txt; as 16-bit 44.1 sw
# concatenate, and record a file of beginnings and durations

my $PROG = '/home/asher/m/dev/apb/lib/sound-engine/synthem80';
my $SPEC = 'spec.txt';
my $RATE = 44100;
my $JS_FILE = 'sounds.auto';

my @names;


open F, $SPEC or die "Can't open $SPEC: $!";
while(<F>) {
    next if /^#/;
    next unless /\S/;
    chomp;
    /^(\w+)\s+(\d+)\s+(\S.*)/ or die "Invalid line: $_";
    my $name = $1;
    push @names, $name;
    my $ms = $2;
    my $spec = $3;
    my $cmd = "$PROG -t$ms -o $name.sw '$spec'";
    print STDERR "$cmd\n";
    unlink("$name.sw");
    system($cmd);
    die "No sw outfile" unless -e "$name.sw";

    $cmd = "sox -r $RATE $name.sw $name.wav";
    print STDERR "$cmd\n";
    system($cmd);
    die "No wav outfile" unless -e "$name.sw";
}

my $js = Dumper(\@names);
$js =~ s/\$VAR1/M.sound_names/;
open F, ">$JS_FILE" or die "Can't open $JS_FILE: $!";
printf F "// autogenerated by $0\n$js// /autogen\n\n";
